### Q) What is numpy and it's use?

* Numpy is an open-source library of python use to perform various mathematical & statistical tasks, such as finding measures of central tendency, covariance & correlation, matrix multiplication, etc.

### Q) What is array?

* Array is a matrix of numerical values which are called elements. Array contains only numerical values. Array can be of any dimension, such as 1D array,  2D array, etc.

### Q) Difference between list and array?

* List contains any data type, such as object, integer, float but array contains only numerical value whether it is interger or float.


* List can be only one dimensional but array can be one dimensional or multi-dimensional.

### Q) How to compute measures of central tendency using numpy?

* We have various functions in numpy to compute measures of central tendency, such as 

* np.mean('column name'), np.median('column name') and to compute mode we have no dirct function in numpy so we use scipy.stats library to compute mode and the code will be scipy.stats.mode('column name') or we use pandas to compute mode by applying df.mode() function which computes mode of every column.

### Q) How to compute percentile?

* We use np.percentile() function and code will be np.percentile('column name', percentile value like 25,50)

### Q) How to convert a list into numpy array?

In [1]:
import numpy as np

a = [1,5,7,6]

numpy_array = np.array(a)

numpy_array # Numpy array results output as a list of elements which are comma seprated 

array([1, 5, 7, 6])

In [2]:
print(numpy_array) # Print a numpy array results in list of elements which are not comma seprated

[1 5 7 6]


In [3]:
a   # list results output in list of elements which are comma seprated. 

[1, 5, 7, 6]

In [4]:
print(a)  # Print a list results same output as object of list

[1, 5, 7, 6]


In [5]:
type(a)

list

In [6]:
type(numpy_array)

numpy.ndarray

### Q) Suppose there is an array [[1,2,3][4,5,6][7,8,9]]. Extract the value 8 using 2D indexing

In [7]:
num = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(num)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
num[2,1]

8

### Q) Suppose there is an array that has values: [0,1,2,3,4,5,6,7,8,9]. How will you display the following values from an array:[1,3,5,7,9]?

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

### Q) How will you print four random integers between 1 to 15 using Numpy?

In [18]:
rand_arr = np.random.randint(1,15,4)
rand_arr

array([ 8,  7, 13,  6])

### Q) There are two arrays 'A', 'B'. Stack the arrays A and B horizontally using the Numby.



In [22]:
A = np.array([1,2,3])
B = np.array([4,5,6])

A,B

(array([1, 2, 3]), array([4, 5, 6]))

In [26]:
np.hstack([A,B])

array([1, 2, 3, 4, 5, 6])

### Q) How to reshape a array?

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr.ndim, arr

(1, array([1, 2, 3, 4, 5, 6]))

In [42]:
reshaped_arr = arr.reshape(2, 3)
reshaped_arr.ndim, reshaped_arr

(2,
 array([[1, 2, 3],
        [4, 5, 6]]))