### Q) What is numpy and it's use?

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

-----------

Numpy is an open-source library of python use to perform various mathematical & statistical tasks, such as finding measures of central tendency, covariance & correlation, matrix multiplication, etc.

-----------------

NumPy is a powerful Python library used for numerical computing. It provides support for multi-dimensional arrays and a wide range of mathematical functions to perform operations efficiently.

### Q) How do you create a NumPy array?
You can create a NumPy array from a Python list using the numpy.array() function:

In [1]:
#Method 1

import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [2]:
type(my_array)

numpy.ndarray

In [15]:
print(my_array[0:3:-1])

[]


**`NOTE`: Reverse slicing doesn't work in numpy**

### Q) How to create a 2D or multi-dimensional array?

In [13]:
#create 2D array

arr = np.array([[1, 2, 3, 4, 5]])
arr.ndim

2

In [14]:
#Create multi-dimensional array

arr = np.array([[[[[1, 2, 3, 4, 5]]]]])
arr.ndim

5

In [22]:
# Method 2

my_array = np.array([[[1],[2],[3]]])
my_array

array([[[1],
        [2],
        [3]]])

In [23]:
my_array.ndim

3

In [27]:
# Method 3

matrix = np.array([[1,2,3],[4,5,6],[5,9,0],[9,8,10],[5,4,5]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  9,  0],
       [ 9,  8, 10],
       [ 5,  4,  5]])

In [28]:
matrix.ndim

2

### Q) How to perform slicing in an array?



**Slicing of Multi-Dimensional Array**

In [29]:
print(matrix[0:2,1:2]) #Rows, Columns

[[2]
 [5]]


In [30]:
matrix[4,-1:]

array([5])

In [44]:
matrix[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [5, 9, 0]])

### Q) How to check minimum and maximum element of an entire array?

In [46]:
# minimum element

np.min(matrix)

0

In [ ]:
# maximum element


np.max(matrix)

### Q) How to check minimum and maximum element of an array, row & column wise?

In [47]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  9,  0],
       [ 9,  8, 10],
       [ 5,  4,  5]])

In [50]:
# Column wise minimum value

np.min(matrix, axis = 0) 

array([1, 2, 0])

In [51]:
# Column wise maximum value

np.max(matrix, axis = 0) 

array([ 9,  9, 10])

In [52]:
# Row wise minimum value

np.min(matrix, axis = 1) 

array([1, 4, 0, 8, 4])

In [53]:
# Row wise maximum value

np.max(matrix, axis = 1) 

array([ 3,  6,  9, 10,  5])

### Q) Calcualte the mean of all rows, columns and  elements of an  array.

In [54]:
# Mean of all elememts

matrix.mean()

5.066666666666666

In [57]:
# Row wise mean

matrix.mean(axi = 1)

array([2.        , 5.        , 4.66666667, 9.        , 4.66666667])

In [58]:
# Column wise mean

matrix.mean(axis = 0)

array([4.8, 5.6, 4.8])

### Q) Count elements and shape of an array.

In [59]:
my_array = np.array([[[1],[2],[3]]])
my_array

array([[[1],
        [2],
        [3]]])

In [60]:
# Counts of elements

my_array.size

3

In [61]:
my_array.shape

(1, 3, 1)

### Q) How to reshape array?

In [62]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  9,  0],
       [ 9,  8, 10],
       [ 5,  4,  5]])

In [66]:
matrix.reshape(3,5) #Rows, Columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  5,  9,  0,  9],
       [ 8, 10,  5,  4,  5]])

In [67]:
matrix.reshape(4,4)

ValueError: cannot reshape array of size 15 into shape (4,4)

**Make sure that elements are equal to the elements in existing array.**

### Q) Perform mathematical functions on 2 arrays, such as addition, subtraction, multiplication.

In [70]:
matrix_1 = np.array([[1,2,3],[6,5,6],[7,7,9]])
matrix_1

array([[1, 2, 3],
       [6, 5, 6],
       [7, 7, 9]])

In [71]:
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])
matrix_2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [72]:
# Adding 2 matrixes

np.add(matrix_1,matrix_2)

array([[ 8, 10, 12],
       [10, 10, 12],
       [ 8,  9, 12]])

In [73]:
# subtracting 2 matrixes

np.subtract(matrix_1,matrix_2)

array([[-6, -6, -6],
       [ 2,  0,  0],
       [ 6,  5,  6]])

In [74]:
# multiplying 2 matrixes

matrix_1*matrix_2

array([[ 7, 16, 27],
       [24, 25, 36],
       [ 7, 14, 27]])

**Mathematical functions are done by positioning of elements.**

### Q) Convert multi-dimensional array into D array.

In [75]:
matrix.ndim

2

In [81]:
x = matrix.flatten()

In [82]:
x.ndim

1

### Q) Output all the unique elements of an array?

In [83]:
a = np.array([1,1,2,2,3,3,5,7,9,9])

In [87]:
np.unique(a)

array([1, 2, 3, 5, 7, 9])

### Q) Generate (5,3) array of random numbers between 0-1.

In [89]:
np.random.rand(5,3)

array([[0.62321331, 0.5239855 , 0.63203553],
       [0.73347264, 0.06844459, 0.31202461],
       [0.92524322, 0.60459505, 0.17576985],
       [0.43412588, 0.26357514, 0.7022545 ],
       [0.06886067, 0.58749658, 0.03398974]])

### Q) Generate (5,3) array of random numbers between 10-20.

In [92]:
np.random.randint(10,20, size = (5,3))

array([[19, 10, 14],
       [14, 15, 15],
       [14, 14, 14],
       [12, 18, 15],
       [18, 13, 16]])

### Q) Round-up and round down the float elemets of an array.

In [93]:
# Round-Up Array

arr = [0.23, 0.09, 1.2, 1.24, 9.99, 101.01]
r_arr = np.ceil(arr)
r_arr

array([  1.,   1.,   2.,   2.,  10., 102.])

In [95]:
# Round-Down Array

r_arr = np.floor(arr)
r_arr

array([  0.,   0.,   1.,   1.,   9., 101.])

  ### Q) How to replace elemets of an array?

In [97]:
#Consider the array as follows
lst=[[110,90,80],[70,60,110],[30,10,20],[50,40,110]]
npm=np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [98]:
# Replace all elements of numpy array with 50
npm[:,:]=50
npm

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [99]:
# Replace 0,0 position with 500
npm[0,0]=500
npm

array([[500,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50],
       [ 50,  50,  50]])

### Q) Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [100]:
a = np.arange(15,56)
print(a[0:-1:2])

[15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53]


In [101]:
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

### Q) Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [104]:
my_list = [1,2,3,4,5,6]

a = np.array(my_list)
l1=list(a)
l1

[1, 2, 3, 4, 5, 6]

In [103]:
type(a)

numpy.ndarray

In [105]:
a.ndim

1

### Q) How to create array using 'FOR' Loop?


In [10]:
l=[]
for i in range(1,5):
    a=int(input("enter:"))
    l.append(a)
print(np.array(l))

enter:5
enter:6
enter:6
enter:6
[5 6 6 6]


### Q) How to chech dimension of an array?

By using .ndim function.

In [4]:
my_array.ndim

1

### Q) What is array?

* Array is a matrix of numerical values which are called elements. Array contains only numerical values. Array can be of any dimension, such as 1D array,  2D array, etc.

### Q) Difference between list and array?

* List contains any data type, such as object, integer, float but array contains only numerical value whether it is interger or float.


* List can be only one dimensional but array can be one dimensional or multi-dimensional.

### Q) What are the key features of NumPy?
NumPy's main feature is the ndarray (n-dimensional array) that allows you to perform operations efficiently on large datasets. It also provides functions for mathematical operations, array slicing, reshaping, and broadcasting.

### Q) How to compute measures of central tendency using numpy?

* We have various functions in numpy to compute measures of central tendency, such as 


* np.mean('column name'), np.median('column name') and to compute mode we have no dirct function in numpy so we use scipy.stats library to compute mode and the code will be scipy.stats.mode('column name') or we use pandas to compute mode by applying df.mode() function which computes mode of every column.

### Q) How to compute percentile?

* We use np.percentile() function and code will be np.percentile('column name', percentile value like 25,50)

### Q) How to convert a list into numpy array?

In [1]:
import numpy as np

a = [1,5,7,6]

numpy_array = np.array(a)

numpy_array # Numpy array results output as a list of elements which are comma seprated 

array([1, 5, 7, 6])

In [2]:
print(numpy_array) # Print a numpy array results in list of elements which are not comma seprated

[1 5 7 6]


In [3]:
a   # list results output in list of elements which are comma seprated. 

[1, 5, 7, 6]

In [4]:
print(a)  # Print a list results same output as object of list

[1, 5, 7, 6]


In [5]:
type(a)

list

In [6]:
type(numpy_array)

numpy.ndarray

### Q) Suppose there is an array [[1,2,3][4,5,6][7,8,9]]. Extract the value 8 using 2D indexing

In [7]:
num = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(num)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
num[2,1]

8

### Q) Suppose there is an array that has values: [0,1,2,3,4,5,6,7,8,9]. How will you display the following values from an array:[1,3,5,7,9]?

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

### Q) How will you print four random integers between 1 to 15 using Numpy?

In [18]:
rand_arr = np.random.randint(1,15,4)
rand_arr

array([ 8,  7, 13,  6])

### Q) There are two arrays 'A', 'B'. Stack the arrays A and B horizontally using the Numby.



In [22]:
A = np.array([1,2,3])
B = np.array([4,5,6])

A,B

(array([1, 2, 3]), array([4, 5, 6]))

In [26]:
np.hstack([A,B])

array([1, 2, 3, 4, 5, 6])

### Q) How to reshape a array?

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr.ndim, arr

(1, array([1, 2, 3, 4, 5, 6]))

In [42]:
reshaped_arr = arr.reshape(2, 3)
reshaped_arr.ndim, reshaped_arr

(2,
 array([[1, 2, 3],
        [4, 5, 6]]))